[package]
name = "mire"
version = "0.1.0"
edition = "2018"
authors = ["Rajat Sharma <lunasunkaiser@gmail.com>"]
description = "Simple Error Handling in Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rajatsharma/mire"

[dependencies]
